export const SET_PAGE_TITLE = 'SET_PAGE_TITLE'

export const SET_AJAX_FLAG = 'SET_AJAX_FLAG'

export const SET_EDIT_FLAG = 'SET_EDIT_FLAG'

export const SET_LOAD_MORE = 'SET_LOAD_MORE'

export const SET_SORT_EDIT_FLAG = 'SET_SORT_EDIT_FLAG'

export const SET_ALBUM_SORT_NAME = 'SET_ALBUM_SORT_NAME'

export const SET_PREVIEW_FLAG = 'SET_PREVIEW_FLAG'

export const SET_REQUEST_PARAMS = 'SET_REQUEST_PARAMS'

export const SET_REQUEST_PARAMS_ORDERBY = 'SET_REQUEST_PARAMS_ORDERBY'

export const SET_REQUEST_PARAMS_DESCENDING = 'SET_REQUEST_PARAMS_DESCENDING'

export const SET_FILES_SHOW_MODE = 'SET_FILES_SHOW_MODE'

export const SET_CURRENT_FOLDER_INFO = 'SET_CURRENT_FOLDER_INFO'

export const SET_SELECTED_FILES = 'SET_SELECTED_FILES'

export const ADD_FILE_PATH = 'ADD_FILE_PATH'

export const ADD_FOLDER_PATH = 'ADD_FOLDER_PATH'

export const DECREASE_FILE_PATH = 'DECREASE_FILE_PATH'

export const SET_FILE_PATH = 'SET_FILE_PATH'

export const SET_FAMILY_INFO = 'SET_FAMILY_INFO'

export const SET_FAMILY_LIST = 'SET_FAMILY_LIST'

export const SET_USER_VIP_INFO = 'SET_USER_VIP_INFO'

export const SET_FAMILY_FILE_LIST = 'SET_FAMILY_FILE_LIST'

export const SET_CLOUD_FILE_LIST = 'SET_CLOUD_FILE_LIST'

export const SET_APP_MODEL = 'SET_APP_MODEL'

export const SET_SDK_CONFIG = 'SET_SDK_CONFIG'

export const SET_FAMILY_LIST_TYPE = 'SET_FAMILY_LIST_TYPE'

export const SET_FAMILY_TAB_INDEX = 'SET_FAMILY_TAB_INDEX'

export const SET_ALBUM_TAB_INDEX = 'SET_ALBUM_TAB_INDEX'

export const SET_APPEND_FLAG = 'SET_APPEND_FLAG'

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'

export const SET_TABBAR_FLAG = 'SET_TABBAR_FLAG'

export const SET_JUMP_BY_CLICK = 'SET_JUMP_BY_CLICK'

export const SET_AdAPT_IPHONEX = 'SET_AdAPT_IPHONEX'

export const SET_SHOW_SDK_UPLOAD_BTN = 'SET_SHOW_SDK_UPLOAD_BTN'

export const SET_USER_INFO = 'SET_USER_INFO'